### ISSUE TITLE
dockerapp-dockerapp-1 exited with code 1 - Task 8 in Lab 2

### ISSUE THREAD

**Issue by kzyr6573** [inwk6312course/dockerapp#7]
Hi Tito and Majid,

Yesterday we had Lab 2, when it came to Task 8, it seemed that the `docker-compose up` didn't bring up 2 containers as expected, when following steps in the lab manual, and Tito also came across this problem later when presenting this lab:
```
$ docker-compose up                                  
[+] Running 8/8
 ✔ redis 7 layers [⣿⣿⣿⣿⣿⣿⣿]      0B/0B      Pulled                                                                                          4.8s 
   ✔ 51f5c6a04d83 Pull complete                                                                                                             3.1s 
   ✔ 6c8ccd839b1d Pull complete                                                                                                             3.2s 
   ✔ 0fded1c9651d Pull complete                                                                                                             3.7s 
   ✔ 7f1aa6a73799 Pull complete                                                                                                             3.8s 
   ✔ 658be2e58dbd Pull complete                                                                                                             4.0s 
   ✔ 3d3b67be53f9 Pull complete                                                                                                             4.1s 
   ✔ 8a88e1919daf Pull complete                                                                                                             4.2s 
[+] Building 0.5s (10/10) FINISHED                                                                                                               
 => [internal] load build definition from Dockerfile                                                                                        0.0s
 => => transferring dockerfile: 196B                                                                                                        0.0s
 => [internal] load .dockerignore                                                                                                           0.0s
 => => transferring context: 2B                                                                                                             0.0s
 => [internal] load metadata for docker.io/library/python:3.10                                                                              0.4s
 => [internal] load build context                                                                                                           0.0s
 => => transferring context: 132B                                                                                                           0.0s
 => [1/5] FROM docker.io/library/python:3.10@sha256:69a1e3bde8f6d3f1b5a9d3025daa24ccd76ecfe833be1d36cc3fcdf383b575f2                        0.0s
 => => resolve docker.io/library/python:3.10@sha256:69a1e3bde8f6d3f1b5a9d3025daa24ccd76ecfe833be1d36cc3fcdf383b575f2                        0.0s
 => CACHED [2/5] RUN pip install Flask==0.11.1 redis==2.10.5                                                                                0.0s
 => CACHED [3/5] RUN useradd -ms /bin/bash admin                                                                                            0.0s
 => CACHED [4/5] WORKDIR /app                                                                                                               0.0s
 => CACHED [5/5] COPY app /app                                                                                                              0.0s
 => exporting to image                                                                                                                      0.0s
 => => exporting layers                                                                                                                     0.0s
 => => writing image sha256:e29f51bfce29030295f3f04dc89aeb8ab7d4c272474ee7c76098e83d7e10df7f                                                0.0s
 => => naming to docker.io/library/dockerapp-dockerapp                                                                                      0.0s
[+] Running 3/3
 ✔ Network dockerapp_default        Created                                                                                                 0.1s 
 ✔ Container dockerapp-redis-1      Created                                                                                                 0.0s 
 ✔ Container dockerapp-dockerapp-1  Created                                                                                                 0.0s 
Attaching to dockerapp-dockerapp-1, dockerapp-redis-1
dockerapp-redis-1      |                 _._                                                  
dockerapp-redis-1      |            _.-``__ ''-._                                             
dockerapp-redis-1      |       _.-``    `.  `_.  ''-._           Redis 3.2.0 (00000000/0) 64 bit
dockerapp-redis-1      |   .-`` .-```.  ```\/    _.,_ ''-._                                   
dockerapp-redis-1      |  (    '      ,       .-`  | `,    )     Running in standalone mode
dockerapp-redis-1      |  |`-._`-...-` __...-.``-._|'` _.-'|     Port: 6379
dockerapp-redis-1      |  |    `-._   `._    /     _.-'    |     PID: 1
dockerapp-redis-1      |   `-._    `-._  `-./  _.-'    _.-'                                   
dockerapp-redis-1      |  |`-._`-._    `-.__.-'    _.-'_.-'|                                  
dockerapp-redis-1      |  |    `-._`-._        _.-'_.-'    |           http://redis.io        
dockerapp-redis-1      |   `-._    `-._`-.__.-'_.-'    _.-'                                   
dockerapp-redis-1      |  |`-._`-._    `-.__.-'    _.-'_.-'|                                  
dockerapp-redis-1      |  |    `-._`-._        _.-'_.-'    |                                  
dockerapp-redis-1      |   `-._    `-._`-.__.-'_.-'    _.-'                                   
dockerapp-redis-1      |       `-._    `-.__.-'    _.-'                                       
dockerapp-redis-1      |           `-._        _.-'                                           
dockerapp-redis-1      |               `-.__.-'                                               
dockerapp-redis-1      | 
dockerapp-redis-1      | 1:M 10 May 16:51:13.034 # Server started, Redis version 3.2.0
dockerapp-redis-1      | 1:M 10 May 16:51:13.034 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
dockerapp-redis-1      | 1:M 10 May 16:51:13.034 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
dockerapp-redis-1      | 1:M 10 May 16:51:13.034 * The server is now ready to accept connections on port 6379
dockerapp-dockerapp-1  | Traceback (most recent call last):
dockerapp-dockerapp-1  |   File "/app/app.py", line 1, in <module>
dockerapp-dockerapp-1  |     from flask import Flask, request, render_template
dockerapp-dockerapp-1  |   File "/usr/local/lib/python3.10/site-packages/flask/__init__.py", line 19, in <module>
dockerapp-dockerapp-1  |     from jinja2 import Markup, escape
dockerapp-dockerapp-1  | ImportError: cannot import name 'Markup' from 'jinja2' (/usr/local/lib/python3.10/site-packages/jinja2/__init__.py)
dockerapp-dockerapp-1 exited with code 1
```
I searched the second last line `ImportError: cannot import name 'Markup' from 'jinja2' (/usr/local/lib/python3.10/site-packages/jinja2/__init__.py)`, there is [a question on StackExchange](https://stackoverflow.com/questions/71645272/importerror-cannot-import-name-markup-from-jinja2) describing the same error. [One of the answers](https://stackoverflow.com/a/71645733) mentioned that the error comes from calling `jinja2.Markup()` without arguments (see [release note](https://jinja.palletsprojects.com/en/3.1.x/changes/#version-3-0-1) and [issue](https://github.com/pallets/jinja/issues/1438)). [Another answer](https://stackoverflow.com/a/71647006) says that upgrading Flask to 2.0.3 can fix the issue. Honestly I don't know the reason you choose the version of Flask and Jinja in this Dockerfile, but I have forked the repo and changed the version of Flask from 0.11.1 to 2.0.3 in [this commit](https://github.com/kzyr6573/dockerapp/commit/0eab338bfb4904d9eb9c80ea5c835bb19f22b06c). I can make a pull request if you think it can be accepted, or maybe you have your reasons to use specific versions of packages. Just trying to practice contributing to public repos, even if it is a minor change.

**Comment by inwk6312course** [comment]
Hi  @kzyr6573  
Thanks for opening this issue. Yes i have come across the error too  and i think the Flask version change is the solution.
In the spirit of collaboration, can you make a pull request and i will merge the change. 
Thanks a lot.

Tito

**Comment by kzyr6573** [comment]
Sure, thanks Tito for accepting this minor fix.
